name: Deploy ANITRAX Contract to Casper Testnet

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2026-01-01
          target: wasm32-unknown-unknown

      - name: Install Casper Client
        run: |
          cargo install casper-client

      - name: Build ANITRAX Contract
        run: |
          cargo +nightly-2026-01-01 build --target wasm32-unknown-unknown --bin anitrax_contract_build_contract --release --features build-contract

      - name: Prepare Secret Key
        env:
          SECRET_KEY: ${{ secrets.CASPER_SECRET_KEY }}
        run: |
          echo "$SECRET_KEY" > secret_key.pem
          chmod 600 secret_key.pem

      - name: Check files
        run: |
          ls -la
          ls -la target/wasm32-unknown-unknown/release

      - name: Deploy Contract
        run: |
          casper-client put-deploy \
          --node-address https://node.testnet.casper.network:7777 \
          --chain-name casper-test \
          --secret-key secret_key.pem \
          --session-path target/wasm32-unknown-unknown/release/anitrax_contract_build_contract.wasm \
          --payment-amount 3000000000
